_target_: dos.components.diffusion_model_text_to_image.diffusion_sds.DiffusionForTargetImg # Class Name
output_dir: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/outputs
# init_image_path: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-front-1.png
# init_image_path: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-back-1.png
init_image_path: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-side-1.png
vis_name: cow-sds_latent-l2_image-sd_XL-600-lr1e-1.png
prompts: "a photograph of a single cow running very fast, back view"
negative_prompts: "front view, side view"
mode: sds_latent-l2_image # sds_image #
lr: 0.1  # For DeepFloyd
lr_l2: 1e4  # For SD+SDS
seed: 2
num_inference_steps: 50
guidance_scale: 20
image_fr_path: True
select_diffusion_option: sd_XL # Options are sd, sd_XL, df, sd_dds_loss  # by default is sds loss
