_target_: dos.components.diffusion_model_text_to_image.diffusion_sds.DiffusionForTargetImg # Class Name
output_dir: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/outputs
# init_image_path: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-front-1.png
# init_image_path: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-back-1.png
# init_image_path: [/scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-side-1.png, /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-back-1.png]
# init_image_path: [/scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-front-1.png, /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-side-1.png, /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-back-1.png]
init_image_path: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-*.png
# init_image_path: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-side-1.png
vis_name: cow-batch-sds_latent_decenc-600-lr2e-1-2np-mom0.2.jpg
prompts: "a photograph of a single cow running very fast, back view, back view"
negative_prompts: "front view, side view, front view, side view"
mode: sds_latent_decenc
lr: 0.1 
momentum: 0.2
seed: 2
num_inference_steps: 50
guidance_scale: 20
image_fr_path: True
save_visuals_every_n_iter: 4
schedule: "[600] * 50"
