_target_: dos.components.diffusion_model_text_to_image.diffusion_sds.DiffusionForTargetImg # Class Name
output_dir: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/outputs
# init_image_path: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-front-1.png
# init_image_path: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-back-1.png
# init_image_path: [/scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-side-1.png, /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-back-1.png]
# init_image_path: [/scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-front-1.png, /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-side-1.png, /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-back-1.png]
init_image_path: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-*.png
# init_image_path: /scratch/shared/beegfs/tomj/dos/articulator/sds_exploration/cow/inputs/cow-side-1.png
vis_name: cow-batch-sds_latent-600-lr2.5e-1-2np-mom0.4-20s.jpg
prompts: "a photograph of a single cow running very fast, back view, back view"
negative_prompts: "front view, side view, front view, side view"
mode: sds_latent
lr: 0.25
momentum: 0.4
seed: 2
num_inference_steps: 20
guidance_scale: 20
image_fr_path: True
save_visuals_every_n_iter: 4
schedule: "[600] * 50"
