_target_: dos.trainer.Trainer

train_dataset:
  _target_: dos.datasets.ImageDataset
  root_dir: /scratch/shared/beegfs/tomj/projects/articulator/magicpony_predictions/synth_animals/horse-articulator-v1.0
  attributes:
    - name: image
      suffix: _image_gt.png
    - name: mask
      suffix: _mask_gt.png
    - name: pose
      suffix: _pose.txt
    - name: mesh
      suffix: _prior_mesh.obj
    - name: texture_features
      suffix: _texture_features.pth

model:
  _target_: dos.models.articulator.Articulator
  texture_predictor:
    _target_: dos.predictors.texture.TexturePredictor
  bones_predictor:
    _target_: dos.components.skinning.bones_estimation.BonesEstimator
    num_body_bones: 8
    num_leg_bones: 3
    body_bones_type: z_minmax_y+
    temperature: 0.05
  articulation_predictor:
    _target_: dos.predictors.articulation_predictor.ArticulationPredictor
    size_dataset: 49
    num_bones: 20


  renderer:
    _target_: dos.modules.renderer.Renderer
    cam_pos_z_offset: 13.5 # roughly compensate bias in the training dataset (now the horse is smaller)
  

modules_to_load:
  - name: texture_predictor.net_texture
    path: /scratch/shared/beegfs/tomj/articulator/data/magicpony/netTexture_horse.pth

checkpoint_root_dir: /scratch/shared/beegfs/oishideb/articulator/logs
experiment_name: articulator-dev-0.1

device: cuda:0

# num_iterations: 10000
# resume: True

learning_rate: 0.9

# for debugging
num_iterations: 100
num_vis_iterations: 10
num_eval_iterations: 10
# save_checkpoint_freq: 10
num_workers: 0
batch_size: 12
